### ISSUE TITLE
Use of PyQt5>=5.15.6 in requirements

### ISSUE THREAD

**Issue by goanpeca** [AdaptiveMotorControlLab/CellSeg3d#13]
Hello 👋🏼 

We are in the process of creating conda packages for [napari plugins](https://www.napari-hub.org/) and related dependencies. Once this recipe passes all the checks, every time a new release goes into PyPI, a PR will be created automatically, with usually very minor need for changes so the process of maintaining this moving forward is small. Also the `@conda-forge/napari` team will be available to help as needed.

You can read a bit more about conda-forge at https://conda-forge.org/#contribute

---

In the creation of the recipe (https://github.com/conda-forge/staged-recipes/pull/19538) I noted some issues:

1. Using PyQt5 as dependency https://github.com/AdaptiveMotorControlLab/CellSeg3d/blob/main/setup.cfg#L45 instead of qtpy
You can read more about why here -> https://napari.org/plugins/best_practices.html#best-practices

2. is there any reason to use Qt>=5.15 ? Currently conda fortge supports upto 5.12, so if this constrained cannot be relaxed, it means this package will not be available for installation withing the napari bundle application (that relies con conda and conda-forge packages)
3. opencv is pinned to 4.5.5.62, and the latest available on conda-forge is v4.5.5. could this be relaxed as well?
4. itk is pinned to itk ==5.2.0.post1, could this be relaxed as well?
---

Do you think these issues could be addressed and have a new version?

I can offer guidance as needed :) 

Cheers and thanks!

**Comment by C-Achard** [comment]
Hello @goanpeca , thank you very much for your feedback ! 

I quickly edited the requirements in setup.cfg and requirements.txt, let me know if everything is okay.

- I switched from PyQt5>=5.15 to PyQt, I hope this is okay (I missed the fact that we were explicitely using it in the reqs instead of qtpy). Would this work with the 5.12 constraint on conda-forge ?
- itk post1 was a remnant of pypi-test issues, it has been changed to >= 5.2.0
- opencv relaxed to >= 4.5.5

Regarding the PR on staged-recipes, I think you can add me as maintainer :)

Thanks again !

**Comment by goanpeca** [comment]
Hi @C-Achard, thanks for the changes :), I think they look good!
