### ISSUE TITLE
Apply inference to a single image that's already open (feature request?)

### ISSUE THREAD

**Issue by haesleinhuepf** [AdaptiveMotorControlLab/CellSeg3d#7]
Hi all,

wow, I'm amazed to see this new plugin out!

I just attempted to try it out on a single image (exemple data provided by the [cellpose-napari](https://www.napari-hub.org/plugins/cellpose-napari) plugin) and I was wondering if it might be possible to apply specific cellseg3d-models to an image that's currently open in napari? 

![image](https://user-images.githubusercontent.com/12660498/175800871-67768c3a-4504-46db-bd4f-a5e0842ebd09.png)

The [docs](https://adaptivemotorcontrollab.github.io/CellSeg3d/res/guides/inference_module_guide.html) suggest to save images to a folder so that I can then apply cellseg3d to that folder. That seems complicated. Let me know if I misunderstood the docs.

No hurry though. And congrats everyone. This tool seems extremely useful!

Best,
Robert

**Comment by MMathisLab** [comment]
Hey @haesleinhuepf thanks so much! Fast find :) 

Indeed a to-do on our list (we designed it in mind to take the whole brains then cropped and store those crops into a directory, so that was the rationale), but agree a "drag and drop" is a useful add that napari excels at :) ! 

- also, right now the model download is a WIP for Monday, so you'll have to "load custom weights" for the time being, but you can grab here: https://github.com/AdaptiveMotorControlLab/CellSeg3d/pull/6/commits/2743787cd7abf447f37eea761abc29342b2414ea

**Comment by MMathisLab** [comment]
Also, just to clarify, you can run it on a single image, just right now you need to select the directory (but if only one image in there, no problem!)

**Comment by haesleinhuepf** [comment]
> take the whole brains then cropped and store those crops into a directory, so that was the rationale

I guess most users (at least in my local environment) have suitable data that's small enough so that it doesn't need to be tiled. 

Looking forward to updates 🌻

**Comment by MMathisLab** [comment]
update, rc2 now has model downloads fully functional, more soon!

**Comment by C-Achard** [comment]
Hello @haesleinhuepf, your feature request has been added and merged in PR #26 !

We will most likely add it soon to the next patch on Pypi, in the meantime you could try it by installing locally. 

Let us know if you have further feedback on it or other requests regarding the feature!
