### ISSUE TITLE
Failed to import command at 'napari_cellseg3d.plugins:Helper': mutable default <class 'napari_cellseg3d.config.Zoom'> for field zoom is not allowed: use default_factory

### ISSUE THREAD

**Issue by edwardando** [AdaptiveMotorControlLab/CellSeg3d#83]
We're trying to get CellSeg3D to work on linux with python 3.11
We have tried napari 0.4.18 and 0.4.19 and after successfully installing the plugin with pip and not conda (it appears in the napari dropdown menu) we get:

```
CellSeg3d-venv/lib/python3.11/site-packages/npe2/_command_registry.py:34, in CommandHandler.resolve(self=CommandHandler(id='napari_cellseg3d.help', funct...e, python_name='napari_cellseg3d.plugins:Helper'))
     32     self.function = utils.import_python_name(self.python_name)
     33 except Exception as e:
---> 34     raise RuntimeError(
        self.python_name = 'napari_cellseg3d.plugins:Helper'
        self = CommandHandler(id='napari_cellseg3d.help', function=None, python_name='napari_cellseg3d.plugins:Helper')
     35         f"Failed to import command at {self.python_name!r}: {e}"
     36     ) from e
     38 return self.function

RuntimeError: Failed to import command at 'napari_cellseg3d.plugins:Helper': mutable default <class 'napari_cellseg3d.config.Zoom'> for field zoom is not allowed: use default_factory
```

This happens when we click on any menu (including "Help/About...") with or without an image loaded

**Comment by C-Achard** [comment]
Hello, thanks for trying the plugin !

I'm afraid the plugin is currently only compatible with python 3.8 to 3.10, this is most likely due to the fact you are using python 3.11.

However, if your use case for the plugin requires python 3.11, please let me know and we could have a look at updating the code to work with it.

Hope this helps ! Please let me know if you encounter any other problems during the install process.

**Comment by MMathisLab** [comment]
https://www.napari-hub.org/plugins/napari-cellseg3d#requirements
