### ISSUE TITLE
detection on large cropped data

### ISSUE THREAD

**Issue by louloupivron** [AdaptiveMotorControlLab/CellSeg3D#89]
Hello Cyril, 

The plugin is great and working fine on our data without retraining the models if we stick to small hundred-pixels-large 3d cropped volumes. But if we try to scale up to larger regions of the dataset, artifacts are biasing the detection. Is it even made for such data ? How would you advise to scale up the segmentation for the full dataset (180Gb large) ? 

![Capture](https://github.com/user-attachments/assets/ddf497ea-d0a6-4046-831a-d8c67705de65)
![large_crop_inference](https://github.com/user-attachments/assets/d410b0f2-b0b9-4ae7-9ba4-fb9f09affe90)

Appreciate your help !

Louis

**Comment by C-Achard** [comment]
Hey Louis, 

Nice to hear from you again, hope you're well !

-  For the kind of artifacts you show I would recommend using the instance segmentation option for artifact removal

Basically it will perform a specific form of instance segmentation and remove all found instance labels that are larger than specified. It should be shown when you select instance segmentation on the latest version of the plugin.
If it does not work well please let me know, maybe we can come up with a more suitable filtering.

- Just make sure to find a suitable threshold value first for the semantic output

You can do so using the contrast sliders on the semantic segmentation output; to me it seems your instance segmentation output might be empty because of the threshold value (semantic output looks fine, aside from artifacts)
In my experience this helped a lot to exclude artifacts when coupled with running the segmentation on certain regions after brain registration.

- As for scaling up to a 180 Gb dataset, I assume this is the full brain ? I personally would not recommend running on the full brain, but choosing regions of interest (e.g. via registration) and then running the segmentation.

Technically I'm sure you can run on the full brain, for example you could fragment it into fairly large cubes and reconstruct it afterwards, but then you will have to go back and remove those volumes on which the segmentation cannot really work anyway - which is why I'd recommend the other way around : isolate ROIs that make sense for your question, and then run segmentation.


Hope this helps !

Best,
Cyril

**Comment by louloupivron** [comment]
Thanks a lot for the quick reply ! I should be working on it next week so I will let you know if anything goes wrong from what you suggested. 

Appreciate your help 👍

**Comment by MMathisLab** [comment]
will close for now, but do let us know how it goes!
