### ISSUE TITLE
Specification of input data

### ISSUE THREAD

**Issue by haesleinhuepf** [AdaptiveMotorControlLab/CellSeg3d#9]
Hi again,

I just went a bit through the docs searching for information about what kind of data (staining) is suitable. E.g. on [this page](https://adaptivemotorcontrollab.github.io/CellSeg3d/res/guides/detailed_walkthrough.html#preparing-images-and-labels) it appears the plugin is used for nuclei detection. Can it also segment cells in images with membrane staining?

Thanks!

Best,
Robert

**Comment by MMathisLab** [comment]
Hey! right now models are trained on cleared brain data (+ general histology, depending on model if from monai or not) mainly with cFOS staining (since this was the hardest data we needed to process), but in the coming weeks/months we will be also training more with endo. flou. Also very happy for more data if others have it // the transfer learning training in the package should allows for you to use with any 3D GT data. The trailmap project was trained on axons originally as well, so I if they want to train w/their data for our pytorch implementation of their model (talking with them :), we'd be happy to host that too.
